services:
  - type: web
    name: creche-ong
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python init_db.py && python popular_banco.py && gunicorn -w 1 -b 0.0.0.0:${PORT:-5000} wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false