"""tabelas crianca e familiar

Revision ID: 7a3efb36e23c
Revises: 
Create Date: 2026-05-23 16:54:18.585675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a3efb36e23c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('criancas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('sexo', sa.String(length=1), nullable=False),
    sa.Column('turno', sa.String(length=10), nullable=False),
    sa.Column('alergias', sa.Text(), nullable=True),
    sa.Column('problemas_medicos', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('foto_documento', sa.String(length=300), nullable=True),
    sa.Column('foto_vacina', sa.String(length=300), nullable=True),
    sa.Column('foto_matricula', sa.String(length=300), nullable=True),
    sa.Column('foto_bolsa_familia', sa.String(length=300), nullable=True),
    sa.Column('foto_comp_residencia', sa.String(length=300), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('familiares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crianca_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('parentesco', sa.String(length=50), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('autorizado_buscar', sa.Boolean(), nullable=True),
    sa.Column('foto_documento', sa.String(length=300), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['crianca_id'], ['criancas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('familiares')
    op.drop_table('criancas')
    # ### end Alembic commands ###
